# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

societe = Archipel.create(libelle: 'société')
Ile.create(libelle: 'tahiti', archipels_id: societe.id)
Ile.create(libelle: 'moorea', archipels_id: societe.id)
Ile.create(libelle: 'bora-bora', archipels_id: societe.id)
Ile.create(libelle: 'huahine', archipels_id: societe.id)
Ile.create(libelle: 'tahaa', archipels_id: societe.id)
Ile.create(libelle: 'raiatea', archipels_id: societe.id)
Ile.create(libelle: 'maupiti', archipels_id: societe.id)

marquises = Archipel.create(libelle: 'marquises')
Ile.create(libelle: 'fatu-hiva', archipels_id: marquises.id)
Ile.create(libelle: 'mohotani', archipels_id: marquises.id)
Ile.create(libelle: 'fatu huku', archipels_id: marquises.id)
Ile.create(libelle: 'hiva-oa', archipels_id: marquises.id)
Ile.create(libelle: 'eiao', archipels_id: marquises.id)
Ile.create(libelle: 'hatu iti', archipels_id: marquises.id)
Ile.create(libelle: 'hatutaa', archipels_id: marquises.id)
Ile.create(libelle: 'nuku-hiva', archipels_id: marquises.id)
Ile.create(libelle: 'tahuata', archipels_id: marquises.id)
Ile.create(libelle: 'ua-huka', archipels_id: marquises.id)
Ile.create(libelle: 'ua-pao', archipels_id: marquises.id)

australes = Archipel.create(libelle: 'australes')
Ile.create(libelle: 'raivavae', archipels_id: australes.id)
Ile.create(libelle: 'marotiri', archipels_id: australes.id)
Ile.create(libelle: 'rapa', archipels_id: australes.id)
Ile.create(libelle: 'rimatara', archipels_id: australes.id)
Ile.create(libelle: 'rurutu', archipels_id: australes.id)
Ile.create(libelle: 'tubuai', archipels_id: australes.id)

tg = Archipel.create(libelle: 'tuamotu-gambier')
Ile.create(libelle: 'anaa', archipels_id: tg.id)
Ile.create(libelle: 'faaite', archipels_id: tg.id)
Ile.create(libelle: 'motutunga', archipels_id: tg.id)
Ile.create(libelle: 'tahanea', archipels_id: tg.id)
Ile.create(libelle: 'apataki', archipels_id: tg.id)
Ile.create(libelle: 'arutua', archipels_id: tg.id)
Ile.create(libelle: 'kaukura', archipels_id: tg.id)
Ile.create(libelle: 'fakarava', archipels_id: tg.id)
Ile.create(libelle: 'raraka', archipels_id: tg.id)
Ile.create(libelle: 'taiaro', archipels_id: tg.id)
Ile.create(libelle: 'niau', archipels_id: tg.id)
Ile.create(libelle: 'fangatau', archipels_id: tg.id)
Ile.create(libelle: 'fakahina', archipels_id: tg.id)
Ile.create(libelle: 'akamaru', archipels_id: tg.id)
Ile.create(libelle: 'angakauitai', archipels_id: tg.id)
Ile.create(libelle: 'aukena', archipels_id: tg.id)
Ile.create(libelle: 'kamaka', archipels_id: tg.id)
Ile.create(libelle: 'makaroa', archipels_id: tg.id)
Ile.create(libelle: 'mangareva', archipels_id: tg.id)
Ile.create(libelle: 'maniui', archipels_id: tg.id)
Ile.create(libelle: 'taravai', archipels_id: tg.id)
Ile.create(libelle: 'maria est', archipels_id: tg.id)
Ile.create(libelle: 'marutea sud', archipels_id: tg.id)
Ile.create(libelle: 'morane', archipels_id: tg.id)
Ile.create(libelle: 'motureivavao', archipels_id: tg.id)
Ile.create(libelle: 'temoe', archipels_id: tg.id)
Ile.create(libelle: 'tenararo', archipels_id: tg.id)
Ile.create(libelle: 'tenarunga', archipels_id: tg.id)
Ile.create(libelle: 'vahanga', archipels_id: tg.id)
Ile.create(libelle: 'hao', archipels_id: tg.id)
Ile.create(libelle: 'ahunui', archipels_id: tg.id)
Ile.create(libelle: 'hikitake amanu', archipels_id: tg.id)
Ile.create(libelle: 'rekareka', archipels_id: tg.id)
Ile.create(libelle: 'tauere', archipels_id: tg.id)
Ile.create(libelle: 'hereheretue', archipels_id: tg.id)
Ile.create(libelle: 'anuanuraro', archipels_id: tg.id)
Ile.create(libelle: 'anuanurunga', archipels_id: tg.id)
Ile.create(libelle: 'nukutepipi', archipels_id: tg.id)
Ile.create(libelle: 'manuhangi', archipels_id: tg.id)
Ile.create(libelle: 'nengonengo', archipels_id: tg.id)
Ile.create(libelle: 'paraoa', archipels_id: tg.id)
Ile.create(libelle: 'hikueru', archipels_id: tg.id)
Ile.create(libelle: 'reitoru', archipels_id: tg.id)
Ile.create(libelle: 'tekokota', archipels_id: tg.id)
Ile.create(libelle: 'marokau', archipels_id: tg.id)
Ile.create(libelle: 'ravahere', archipels_id: tg.id)
Ile.create(libelle: 'kauehi', archipels_id: tg.id)
Ile.create(libelle: 'vaitepaua', archipels_id: tg.id)
Ile.create(libelle: 'makemo', archipels_id: tg.id)
Ile.create(libelle: 'haraiki', archipels_id: tg.id)
Ile.create(libelle: 'marutea-nord', archipels_id: tg.id)
Ile.create(libelle: 'katiu', archipels_id: tg.id)
Ile.create(libelle: 'hiti', archipels_id: tg.id)
Ile.create(libelle: 'tepoto-sud', archipels_id: tg.id)
Ile.create(libelle: 'tuanake', archipels_id: tg.id)
Ile.create(libelle: 'garumaoa raroia', archipels_id: tg.id)
Ile.create(libelle: 'manihi', archipels_id: tg.id)
Ile.create(libelle: 'ahe', archipels_id: tg.id)
Ile.create(libelle: 'napuka', archipels_id: tg.id)
Ile.create(libelle: 'tepoto-nord', archipels_id: tg.id)
Ile.create(libelle: 'tupana', archipels_id: tg.id)
Ile.create(libelle: 'aratika', archipels_id: tg.id)
Ile.create(libelle: 'nukutavake', archipels_id: tg.id)
Ile.create(libelle: 'pinaki', archipels_id: tg.id)
Ile.create(libelle: 'akiaki', archipels_id: tg.id)
Ile.create(libelle: 'vairaatea', archipels_id: tg.id)
Ile.create(libelle: 'puka-puka', archipels_id: tg.id)
Ile.create(libelle: 'pukarua', archipels_id: tg.id)
Ile.create(libelle: 'rangiroa', archipels_id: tg.id)
Ile.create(libelle: 'makatea', archipels_id: tg.id)
Ile.create(libelle: 'mataiva', archipels_id: tg.id)
Ile.create(libelle: 'tikehau', archipels_id: tg.id)
Ile.create(libelle: 'motutapu', archipels_id: tg.id)
Ile.create(libelle: 'reao', archipels_id: tg.id)
Ile.create(libelle: 'taenga', archipels_id: tg.id)
Ile.create(libelle: 'takaroa', archipels_id: tg.id)
Ile.create(libelle: 'takapoto', archipels_id: tg.id)
Ile.create(libelle: 'tikei', archipels_id: tg.id)
Ile.create(libelle: 'takume', archipels_id: tg.id)
Ile.create(libelle: 'tatakoto', archipels_id: tg.id)
Ile.create(libelle: 'tematangi', archipels_id: tg.id)
Ile.create(libelle: 'vanavana', archipels_id: tg.id)
Ile.create(libelle: 'tureia', archipels_id: tg.id)
Ile.create(libelle: 'vahitahi', archipels_id: tg.id)
