# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

societe = Archipel.create(libelle: 'société')
Ile.create(libelle: 'tahiti', archipel_id: societe.id)
Ile.create(libelle: 'moorea', archipel_id: societe.id)
Ile.create(libelle: 'bora-bora', archipel_id: societe.id)
Ile.create(libelle: 'huahine', archipel_id: societe.id)
Ile.create(libelle: 'tahaa', archipel_id: societe.id)
Ile.create(libelle: 'raiatea', archipel_id: societe.id)
Ile.create(libelle: 'maupiti', archipel_id: societe.id)

marquises = Archipel.create(libelle: 'marquises')
Ile.create(libelle: 'fatu-hiva', archipel_id: marquises.id)
Ile.create(libelle: 'mohotani', archipel_id: marquises.id)
Ile.create(libelle: 'fatu huku', archipel_id: marquises.id)
Ile.create(libelle: 'hiva-oa', archipel_id: marquises.id)
Ile.create(libelle: 'eiao', archipel_id: marquises.id)
Ile.create(libelle: 'hatu iti', archipel_id: marquises.id)
Ile.create(libelle: 'hatutaa', archipel_id: marquises.id)
Ile.create(libelle: 'nuku-hiva', archipel_id: marquises.id)
Ile.create(libelle: 'tahuata', archipel_id: marquises.id)
Ile.create(libelle: 'ua-huka', archipel_id: marquises.id)
Ile.create(libelle: 'ua-pao', archipel_id: marquises.id)

australes = Archipel.create(libelle: 'australes')
Ile.create(libelle: 'raivavae', archipel_id: australes.id)
Ile.create(libelle: 'marotiri', archipel_id: australes.id)
Ile.create(libelle: 'rapa', archipel_id: australes.id)
Ile.create(libelle: 'rimatara', archipel_id: australes.id)
Ile.create(libelle: 'rurutu', archipel_id: australes.id)
Ile.create(libelle: 'tubuai', archipel_id: australes.id)

tg = Archipel.create(libelle: 'tuamotu-gambier')
Ile.create(libelle: 'anaa', archipel_id: tg.id)
Ile.create(libelle: 'faaite', archipel_id: tg.id)
Ile.create(libelle: 'motutunga', archipel_id: tg.id)
Ile.create(libelle: 'tahanea', archipel_id: tg.id)
Ile.create(libelle: 'apataki', archipel_id: tg.id)
Ile.create(libelle: 'arutua', archipel_id: tg.id)
Ile.create(libelle: 'kaukura', archipel_id: tg.id)
Ile.create(libelle: 'fakarava', archipel_id: tg.id)
Ile.create(libelle: 'raraka', archipel_id: tg.id)
Ile.create(libelle: 'taiaro', archipel_id: tg.id)
Ile.create(libelle: 'niau', archipel_id: tg.id)
Ile.create(libelle: 'fangatau', archipel_id: tg.id)
Ile.create(libelle: 'fakahina', archipel_id: tg.id)
Ile.create(libelle: 'akamaru', archipel_id: tg.id)
Ile.create(libelle: 'angakauitai', archipel_id: tg.id)
Ile.create(libelle: 'aukena', archipel_id: tg.id)
Ile.create(libelle: 'kamaka', archipel_id: tg.id)
Ile.create(libelle: 'makaroa', archipel_id: tg.id)
Ile.create(libelle: 'mangareva', archipel_id: tg.id)
Ile.create(libelle: 'maniui', archipel_id: tg.id)
Ile.create(libelle: 'taravai', archipel_id: tg.id)
Ile.create(libelle: 'maria est', archipel_id: tg.id)
Ile.create(libelle: 'marutea sud', archipel_id: tg.id)
Ile.create(libelle: 'morane', archipel_id: tg.id)
Ile.create(libelle: 'motureivavao', archipel_id: tg.id)
Ile.create(libelle: 'temoe', archipel_id: tg.id)
Ile.create(libelle: 'tenararo', archipel_id: tg.id)
Ile.create(libelle: 'tenarunga', archipel_id: tg.id)
Ile.create(libelle: 'vahanga', archipel_id: tg.id)
Ile.create(libelle: 'hao', archipel_id: tg.id)
Ile.create(libelle: 'ahunui', archipel_id: tg.id)
Ile.create(libelle: 'hikitake amanu', archipel_id: tg.id)
Ile.create(libelle: 'rekareka', archipel_id: tg.id)
Ile.create(libelle: 'tauere', archipel_id: tg.id)
Ile.create(libelle: 'hereheretue', archipel_id: tg.id)
Ile.create(libelle: 'anuanuraro', archipel_id: tg.id)
Ile.create(libelle: 'anuanurunga', archipel_id: tg.id)
Ile.create(libelle: 'nukutepipi', archipel_id: tg.id)
Ile.create(libelle: 'manuhangi', archipel_id: tg.id)
Ile.create(libelle: 'nengonengo', archipel_id: tg.id)
Ile.create(libelle: 'paraoa', archipel_id: tg.id)
Ile.create(libelle: 'hikueru', archipel_id: tg.id)
Ile.create(libelle: 'reitoru', archipel_id: tg.id)
Ile.create(libelle: 'tekokota', archipel_id: tg.id)
Ile.create(libelle: 'marokau', archipel_id: tg.id)
Ile.create(libelle: 'ravahere', archipel_id: tg.id)
Ile.create(libelle: 'kauehi', archipel_id: tg.id)
Ile.create(libelle: 'vaitepaua', archipel_id: tg.id)
Ile.create(libelle: 'makemo', archipel_id: tg.id)
Ile.create(libelle: 'haraiki', archipel_id: tg.id)
Ile.create(libelle: 'marutea-nord', archipel_id: tg.id)
Ile.create(libelle: 'katiu', archipel_id: tg.id)
Ile.create(libelle: 'hiti', archipel_id: tg.id)
Ile.create(libelle: 'tepoto-sud', archipel_id: tg.id)
Ile.create(libelle: 'tuanake', archipel_id: tg.id)
Ile.create(libelle: 'garumaoa raroia', archipel_id: tg.id)
Ile.create(libelle: 'manihi', archipel_id: tg.id)
Ile.create(libelle: 'ahe', archipel_id: tg.id)
Ile.create(libelle: 'napuka', archipel_id: tg.id)
Ile.create(libelle: 'tepoto-nord', archipel_id: tg.id)
Ile.create(libelle: 'tupana', archipel_id: tg.id)
Ile.create(libelle: 'aratika', archipel_id: tg.id)
Ile.create(libelle: 'nukutavake', archipel_id: tg.id)
Ile.create(libelle: 'pinaki', archipel_id: tg.id)
Ile.create(libelle: 'akiaki', archipel_id: tg.id)
Ile.create(libelle: 'vairaatea', archipel_id: tg.id)
Ile.create(libelle: 'puka-puka', archipel_id: tg.id)
Ile.create(libelle: 'pukarua', archipel_id: tg.id)
Ile.create(libelle: 'rangiroa', archipel_id: tg.id)
Ile.create(libelle: 'makatea', archipel_id: tg.id)
Ile.create(libelle: 'mataiva', archipel_id: tg.id)
Ile.create(libelle: 'tikehau', archipel_id: tg.id)
Ile.create(libelle: 'motutapu', archipel_id: tg.id)
Ile.create(libelle: 'reao', archipel_id: tg.id)
Ile.create(libelle: 'taenga', archipel_id: tg.id)
Ile.create(libelle: 'takaroa', archipel_id: tg.id)
Ile.create(libelle: 'takapoto', archipel_id: tg.id)
Ile.create(libelle: 'tikei', archipel_id: tg.id)
Ile.create(libelle: 'takume', archipel_id: tg.id)
Ile.create(libelle: 'tatakoto', archipel_id: tg.id)
Ile.create(libelle: 'tematangi', archipel_id: tg.id)
Ile.create(libelle: 'vanavana', archipel_id: tg.id)
Ile.create(libelle: 'tureia', archipel_id: tg.id)
Ile.create(libelle: 'vahitahi', archipel_id: tg.id)
